# Generated by Django 5.0.7 on 2024-07-31 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255, verbose_name='Команда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcommands', to='terminals.command', verbose_name='Родительская команда')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название терминала')),
                ('identifier', models.CharField(max_length=100, unique=True, verbose_name='Идентификатор')),
                ('connected', models.BooleanField(default=False, verbose_name='Подключен')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Терминал',
                'verbose_name_plural': 'Терминалы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Не выполнено')], default='pending', max_length=50, verbose_name='Статус')),
                ('output', models.TextField(blank=True, null=True, verbose_name='Вывод')),
                ('commands', models.ManyToManyField(related_name='tasks', to='terminals.command', verbose_name='Команды')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='terminals.terminal', verbose_name='Терминал')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
