# Generated by Django 5.0.7 on 2024-08-01 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='📅 Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='🔄 Дата обновления'),
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='📅 Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='🔄 Дата обновления'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='📅 Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terminal',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='🔄 Дата обновления'),
        ),
    ]
