# Generated by Django 5.0.7 on 2024-08-01 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0002_command_created_command_updated_task_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название комбинации команд')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='📅 Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='🔄 Дата обновления')),
                ('commands', models.ManyToManyField(related_name='command_sets', to='terminals.command', verbose_name='Команды')),
            ],
            options={
                'verbose_name': 'Комбинация команд',
                'verbose_name_plural': 'Комбинации команд',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название пространства')),
                ('path', models.CharField(max_length=255, verbose_name='Путь к пространству')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='📅 Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='🔄 Дата обновления')),
                ('command_sets', models.ManyToManyField(related_name='spaces', to='terminals.commandset', verbose_name='Комбинации команд')),
            ],
            options={
                'verbose_name': 'Пространство',
                'verbose_name_plural': 'Пространства',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название папки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='📅 Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='🔄 Дата обновления')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='terminals.space', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
            },
        ),
    ]
