# Generated by Django 5.0.7 on 2024-08-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0004_remove_commandset_commands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandset',
            name='commands',
            field=models.ManyToManyField(related_name='command_sets', through='terminals.CommandSetOrder', to='terminals.command', verbose_name='Команды'),
        ),
    ]
