# Generated by Django 5.0.7 on 2024-08-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0005_commandset_commands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='commands',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='terminals.command', verbose_name='Команды'),
        ),
    ]
