# Generated by Django 5.0.7 on 2024-08-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0007_alter_task_commands'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ переменной')),
                ('value', models.CharField(max_length=255, verbose_name='Значение переменной')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='📅 Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='🔄 Дата обновления')),
            ],
            options={
                'verbose_name': 'Переменная окружения',
                'verbose_name_plural': 'Переменные окружения',
            },
        ),
    ]
