# Generated by Django 5.0.7 on 2024-08-04 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0008_environmentvariable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сценария')),
                ('output', models.TextField(blank=True, null=True, verbose_name='Вывод')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='📅 Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='🔄 Дата обновления')),
                ('global_environment_variables', models.ManyToManyField(related_name='scenarios_global', to='terminals.environmentvariable', verbose_name='Общие переменные окружения')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
            },
        ),
        migrations.CreateModel(
            name='ScenarioCommandSetOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='📅 Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='🔄 Дата обновления')),
                ('command_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminals.commandset')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminals.scenario')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='command_sets',
            field=models.ManyToManyField(related_name='scenarios', through='terminals.ScenarioCommandSetOrder', to='terminals.commandset', verbose_name='Комбинации команд'),
        ),
    ]
