# Generated by Django 5.0.7 on 2024-08-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0011_alter_scenario_command_sets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='command_sets',
            field=models.ManyToManyField(blank=True, related_name='scenarios', through='terminals.ScenarioCommandSetOrder', to='terminals.commandset', verbose_name='Комбинации команд'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='global_environment_variables',
            field=models.ManyToManyField(blank=True, related_name='scenarios_global', to='terminals.environmentvariable', verbose_name='Общие переменные окружения'),
        ),
    ]
